<?php

return array(
	'modules/CalendarModule/actions/delete.php'=>'',
	'modules/CalendarModule/actions/edit.php'=>'',
	'modules/CalendarModule/actions/save.php'=>'',
	'modules/CalendarModule/actions/view.php'=>'',
	'modules/CalendarModule/actions/viewday.php'=>'',
	'modules/CalendarModule/actions/viewmonth.php'=>'',
	'modules/CalendarModule/actions/viewweek.php'=>'',
	'modules/CalendarModule/class.php'=>'',
	'modules/CalendarModule/views/Default.config'=>'',
	'modules/CalendarModule/views/Default.tpl'=>'',
	'modules/CalendarModule/views/Mini-Calendar.config'=>'',
	'modules/CalendarModule/views/Mini-Calendar.tpl'=>'',
	'modules/CalendarModule/views/Monthly.config'=>'',
	'modules/CalendarModule/views/Monthly.tpl'=>'',
	'modules/CalendarModule/views/Weekly.config'=>'',
	'modules/CalendarModule/views/Weekly.tpl'=>'',
	'modules/CalendarModule/views/_view.tpl'=>'',
	'modules/CalendarModule/views/_viewday.tpl'=>'',
	'modules/CalendarModule/views/_viewmonth.tpl'=>'',
	'modules/CalendarModule/views/_viewweek.tpl'=>'',
	'modules/CalendarModule/views/_workflowview.tpl'=>'',
	'modules/CalendarModule/views/_form_edit.tpl'=>'',
	'modules/CalendarModule/views/Monthly List.tpl'=>'',
	'modules/CalendarModule/views/Monthly List.config'=>'',
	'datatypes/calendar.php'=>'',
	'datatypes/definitions/calendar.info.php'=>'',
	'datatypes/definitions/calendar.php'=>'',
	'modules/CalendarModule/images/bottomcurve.gif'=>'',
	'modules/CalendarModule/images/topcurve.gif'=>'',
	'modules/CalendarModule/js/postedit.validate.js'=>'',
	'modules/CalendarModule/manifest.php'=>'1',
	'modules/CalendarModule/deps.php'=>'',
	'modules/CalendarModule/actions/delete_form.php'=>'',
	'modules/CalendarModule/actions/process_delete.php'=>'',
	'modules/CalendarModule/views/_form_delete.tpl'=>'',
	'modules/CalendarModule/views/_recur_dates.tpl'=>'',
	'modules/CalendarModule/form.part'=>'',
	'datatypes/definitions/eventdate.php'=>'',
	'modules/CalendarModule/actions/delete_process.php'=>'',
	'datatypes/eventdate.php'=>'',
	'modules/CalendarModule/actions/send_feedback.php'=>'',
	'modules/CalendarModule/views/Administration.tpl'=>'',
	'modules/CalendarModule/views/Default.form'=>'',
	'modules/CalendarModule/views/_cat_viewCategories.tpl'=>'',
	'modules/CalendarModule/views/_feedback_submitted.tpl'=>'',
	'modules/CalendarModule/views/Administration.config'=>'',
	'datatypes/definitions/CalendarModule_config.php'=>'',
	'datatypes/CalendarModule_config.php'=>'',
	'modules/CalendarModule/views/Past Events.tpl'=>'',
	'modules/CalendarModule/views/Upcoming Events.tpl'=>'',
	'modules/CalendarModule/views/Upcoming Events.config'=>'',
	'modules/CalendarModule/views/Upcoming Events.form'=>'',
	'modules/CalendarModule/views/Past Events.form'=>'',
	'modules/CalendarModule/views/Past Events.config'=>'',
	'modules/CalendarModule/views/Upcoming Events - Summary.form'=>'',
	'modules/CalendarModule/views/Upcoming Events - Summary.config'=>'',
	'modules/CalendarModule/views/Upcoming Events - Summary.tpl'=>'',
);

?>