<?php

return array(
	'modules/ContainerModule/actions/delete.php'=>'',
	'modules/ContainerModule/actions/edit.php'=>'',
	'modules/ContainerModule/actions/order.php'=>'',
	'modules/ContainerModule/actions/save.php'=>'',
	'modules/ContainerModule/actions/delete_content.php'=>'',
	'modules/ContainerModule/actions/orphans_modules.php'=>'',
	'modules/ContainerModule/actions/orphans_content.php'=>'',
	'modules/ContainerModule/class.php'=>'',
	'modules/ContainerModule/views/Default.tpl'=>'',
	'modules/ContainerModule/views/_sourcePicker.tpl'=>'',
	'modules/ContainerModule/views/_form_edit.tpl'=>'',
	'modules/ContainerModule/views/_nocontent.tpl'=>'',
	'modules/ContainerModule/views/_lastreferencedelete.tpl'=>'',
	'modules/ContainerModule/views/_orphans_modules.tpl'=>'',
	'datatypes/container.php'=>'',
	'datatypes/definitions/container.php'=>'',
	'datatypes/definitions/locationref.php'=>'',
	'datatypes/definitions/sectionref.php'=>'',
	'modules/ContainerModule/views/_linkPicker.tpl'=>'',
	'modules/ContainerModule/views/Grid - 2x2.tpl'=>'',
	'modules/ContainerModule/views/Three Column.tpl'=>'',
	'modules/ContainerModule/views/Two Column.tpl'=>'',
	'modules/ContainerModule/views/_container.tpl'=>'',
	'modules/ContainerModule/manifest.php'=>'',
	'modules/ContainerModule/nosourceselected.php'=>'',
	'modules/ContainerModule/picked_source.php'=>'',
	'js/ContainerSourceControl.js'=>'',
	'modules/ContainerModule/manifest.php'=>1,
	'modules/ContainerModule/deps.php'=>'',
	'modules/ContainerModule/views/_contentPicker.tpl'=>'',
);

?>