<?php

# Manifest file

return array(
	'modules/NavigationModule/actions/delete.php'=>'',
	'modules/NavigationModule/actions/edit.php'=>'',
	'modules/NavigationModule/actions/manage.php'=>'',
	'modules/NavigationModule/actions/order.php'=>'',
	'modules/NavigationModule/actions/save.php'=>'',
	'modules/NavigationModule/class.php'=>'',
	'modules/NavigationModule/views/_htmleditor.tpl'=>'',
	'modules/NavigationModule/views/Breadcrumb.tpl'=>'',
	'modules/NavigationModule/views/Children Only.tpl'=>'',
	'modules/NavigationModule/views/Collapsing Hierarchy.tpl'=>'',
	'modules/NavigationModule/views/Default.tpl'=>'',
	'modules/NavigationModule/views/Directional.tpl'=>'',
	'modules/NavigationModule/views/Expanding Hierarchy.tpl'=>'',
	'modules/NavigationModule/views/Full Hierarchy.tpl'=>'',
	'modules/NavigationModule/views/Marked Hierarchy.tpl'=>'',
	'modules/NavigationModule/views/Top Nav.tpl'=>'',
	'modules/NavigationModule/views/You Are Here.tpl'=>'',
	'modules/NavigationModule/views/_manager.tpl'=>'',
	'modules/NavigationModule/views/_form_editSection.tpl'=>'',
	'datatypes/definitions/section.php'=>'',
	'datatypes/section.php'=>'',
	'modules/NavigationModule/actions/linker.php'=>'',
	'modules/NavigationModule/actions/delete_template.php'=>'',
	'modules/NavigationModule/actions/edit_page.php'=>'',
	'modules/NavigationModule/actions/edit_properties.php'=>'',
	'modules/NavigationModule/actions/edit_template.php'=>'',
	'modules/NavigationModule/actions/order_templates.php'=>'',
	'modules/NavigationModule/actions/save_properties.php'=>'',
	'modules/NavigationModule/actions/save_template.php'=>'',
	'modules/NavigationModule/actions/view_template.php'=>'',
	'modules/NavigationModule/views/_linker.tpl'=>'',
	'modules/NavigationModule/views/Edit Properties.tpl'=>'',
	'modules/NavigationModule/views/_form_editProperties.tpl'=>'',
	'modules/NavigationModule/views/_form_editTemplate.tpl'=>'',
	'modules/NavigationModule/views/_view_template.tpl'=>'',
	'modules/NavigationModule/nav.php'=>'',
	'datatypes/definitions/section_template.php'=>'',
	'datatypes/section_template.php'=>'',
	'datatypes/section_properties.php'=>'',
	'modules/NavigationModule/manifest.php'=>1,
	'modules/NavigationModule/actions/remove.php'=>'',
	'modules/NavigationModule/actions/add_pagesetpage.php'=>'',
	'modules/NavigationModule/actions/add_section.php'=>'',
	'modules/NavigationModule/actions/edit_contentpage.php'=>'',
	'modules/NavigationModule/actions/edit_externalalias.php'=>'',
	'modules/NavigationModule/actions/edit_internalalias.php'=>'',
	'modules/NavigationModule/actions/manage_pagesets.php'=>'',
	'modules/NavigationModule/actions/save_contentpage.php'=>'',
	'modules/NavigationModule/actions/save_externalalias.php'=>'',
	'modules/NavigationModule/actions/save_internalalias.php'=>'',
	'modules/NavigationModule/actions/save_pagesetpage.php'=>'',
	'modules/NavigationModule/actions/move_standalone.php'=>'',
	'modules/NavigationModule/actions/manage_standalone.php'=>'',
	'modules/NavigationModule/actions/reparent_standalone.php'=>'',
	'modules/NavigationModule/views/_move_standalone.tpl'=>'',
	'modules/NavigationModule/views/_add_whichtype.tpl'=>'',
	'modules/NavigationModule/views/_form_addPagesetPage.tpl'=>'',
	'modules/NavigationModule/views/_form_editContentPage.tpl'=>'',
	'modules/NavigationModule/views/_form_editExternalAlias.tpl'=>'',
	'modules/NavigationModule/views/_form_editInternalAlias.tpl'=>'',
	'modules/NavigationModule/views/_manager_pagesets.tpl'=>'',
	'modules/NavigationModule/views/_manager_standalone.tpl'=>'',

);

?>